spring.application.name=delicia
server.port=8181

spring.data.mongodb.uri=mongodb+srv://<gaurvs>:<gaurvs@7063>@<cluster-url>/delicia?retryWrites=true&w=majority

jwt.secret=ThisIsAVeryLongSecretKeyForDeliciaJWTSigningThatShouldBeAtLeast256BitsLong